version: '3.3'
services: 
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    environment: 
      FLASK_ENV: ${FLASK_ENV:-development}
      PORT: ${PORT-5000}
    command: python run.py